{% set name = "homebase" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/homebase-{{ version }}.tar.gz
  sha256: 9ee008df4298b420852d815e6df488822229c4bd8d571bcd0a454e04232c635e

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - homebase
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dwavesystems/homebase
  summary: A platform independent API for paths in which applications can write data.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - BastianZim
